runners:
  - name: aws-runner
    cloud: aws
    region: eu-west-1
    instance_type: t3.large
    machine_image: ami-0910be1e1d214d762
    labels:
      - "cirun-runner"
    extra_config:
      cache: true # Enable caching
      monitoring: true
      # cache_debug: true
